name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container:
            image: cuaesd/aesd-autotest:24-assignment4-buildroot
            options: --user root -v /home/kristian/Documents/actions-runner/.dl:/github/home/.dl
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          
          - name: Fix flock compatibility
            run: |
              apt-get install -y util-linux 2>/dev/null || true
              printf '#!/bin/sh\nwhile [ "${1#-}" != "$1" ]; do shift; done\nexec "$@"\n' > /usr/local/bin/flock
              chmod +x /usr/bin/flock

          - name: Checkout submodules
            run: git submodule update --init --recursive

          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          - name: Run full test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: ./full-test.sh

          - name: Cleanup
            if: always()
            run: ssh-add -D
